import natural from 'natural'
import LangDetect from 'langdetect'
import jsdom from 'jsdom'
import RiTa from 'rita'
import ChineseTokenizer from 'novel-segment'

const chTokenizer = new ChineseTokenizer();
chTokenizer.useDefault();//load dict
const { JSDOM } = jsdom;
const stemmer = natural.PorterStemmer;
const Analyzer = natural.SentimentAnalyzer;
const sentimentAnalyzers = {
    'eu': new Analyzer("Basque", null, 'senticon'),
    'ca': new Analyzer("Catalan", null, "senticon"),
    'nl': new Analyzer("Dutch", stemmer, 'pattern'),
    'en': new Analyzer("English", stemmer, "afinn"),
    'fr': new Analyzer("French", stemmer, 'pattern'),
    'gl': new Analyzer("Galician", null, 'senticon'),
    'it': new Analyzer("Italian", stemmer, 'pattern'),
    'es': new Analyzer("Spanish", stemmer, 'afinn')
}

export function analyze(data) {
    let toReturn = {};
    //no. of images
    let noOfImg = typeof data === 'string' ? (data.match(/< *img/g) || []).length : 0;

    // no of Links
    let noOfLink = typeof data === 'string' ? (data.match(/< *a/g) || []).length : 0;

    //languages
    let rawlangs = []; // backup one for later
    let fullLangs = []; // full names of the languages
    let wordsInHTML; //make a copy
    if (typeof data === 'string') {
        let languages = data.match(/lang *= *(['"a-zA-Z\-])+/g);
        if (languages) {
            let langs = []
            languages.forEach(l => {
                let raw = l.replace(/lang *= */, "");
                raw = raw.replace(/['"]/g, "");
                raw = raw.trim();
                rawlangs.push(raw.slice(0, 2).toLowerCase());
                fullLangs.push(LANGTABLE[raw.slice(0, 2).toLowerCase()] || raw.slice(0, 2).toLowerCase());
            });
        }
        // use detectlanguage api
        wordsInHTML = processHTML(data);
        let words = wordsInHTML.join("");
        let mostLike = LangDetect.detect(words) && LangDetect.detect(words)[0].prob > 0.5 ? LangDetect.detect(words)[0] : undefined;
        if (mostLike !== undefined) {
            let iso2 = mostLike.lang.trim().toLowerCase().substring(0, 2);
            if (!rawlangs.includes(iso2)) rawlangs.push(iso2);
            if (!fullLangs.includes(iso2) && !fullLangs.includes(LANGTABLE[iso2])) fullLangs.push(LANGTABLE[iso2] || iso2);
        }
    }

    // words count && sentiment check
    let wordcount;
    let sentiment;
    if (typeof data === 'string') {
        if (wordsInHTML === undefined) wordsInHTML = processHTML(data);
        let arr = wordsInHTML;
        if (rawlangs.length > 0 && (getMostUsedLang(rawlangs).toLowerCase() === 'cn') || (getMostUsedLang(rawlangs).toLowerCase() === 'zh')) {
            //chinese tokenizer 
            let str = arr.join("");
            str = str.replace(/\s/g, "");
            wordsInHTML = chTokenizer.doSegment(str, { simple: true, stripPunctuation: true });
            wordcount = wordsInHTML.length;
        } else {
            //tokenize with RiTa
            wordcount = arr.length;
        }
        let useLang = rawlangs.length > 0 ? getMostUsedLang(rawlangs) : 'en'; //default = en
        if (sentimentAnalyzers[useLang] !== undefined) sentiment = sentimentAnalyzers[useLang].getSentiment(arr);
    }
    //keywords
    let keywords = [];
    if (wordsInHTML !== undefined) {
        let str = wordsInHTML.join(" ");
        let kwic = RiTa.concordance(str, {
            ignoreCase: true,
            ignoreStopWords: true,
            ignorePunctuation: true,
            wordsToIgnore: notKeywords
        })
        if (kwic && Object.keys(kwic).length > 0) {
            let sortable = [];
            for (let w in kwic) {
                sortable.push([w, kwic[w]]);
            }
            sortable.sort((a, b) => {
                if (a[1] !== b[1]) return b[1] - a[1]; // first sort by frq
                return b[0].length - a[0].length; // if same frq sort by word length
            });
            //console.log(sortable);
            let first5 = sortable.slice(0, Math.min(sortable.length, 8));
            keywords = first5;
        }
    }


    if (noOfImg > 0) toReturn.noOfImg = noOfImg;
    if (noOfLink > 0) toReturn.noOfLink = noOfLink;
    if (fullLangs.length > 0) toReturn.langs = fullLangs;
    if (wordcount !== undefined && wordcount > 0) toReturn.wordCount = wordcount;
    if (sentiment !== undefined) toReturn.sentiment = sentiment;
    if (keywords.length > 0) toReturn.keywords = keywords;
    if (wordsInHTML && wordsInHTML.length > 0) toReturn.words = wordsInHTML;
    return toReturn;
}

function processHTML(str) {
    let raws = str;
    let dom = new JSDOM(raws);
    let body = dom.window.document.body;
    let scripts = body.getElementsByTagName("script");
    let i = scripts.length;
    while (i--) {
        scripts[i].parentNode.removeChild(scripts[i]);
    }
    let styles = body.getElementsByTagName("style");
    let ii = styles.length;
    while (ii--) {
        styles[ii].parentNode.removeChild(styles[ii]);
    }
    let text = body.textContent;
    text = text.replace(/\n/g, " ");
    return RiTa.tokenize(text);
}

function getMostUsedLang(arr) {
    if (!arr || arr.length === 0) return "";
    let o = {};
    arr.forEach(l => {
        let s = l.slice(0, 2);
        if (!o.hasOwnProperty(s)) {
            o[s] = 1;
        } else {
            o[s] += 1;
        }
    });
    let sortable = []
    for (let s in o) {
        sortable.push([s, o[s]]);
    }

    sortable.sort((a, b) => { return b[1] - a[1] });
    return sortable[0][0];
}

const LANGTABLE = {
    ab: "Abkhazian",
    aa: "Afar",
    af: "Afrikaans",
    ak: "Akan",
    sq: "Albanian",
    am: "Amharic",
    ar: "Arabic",
    an: "Aragonese",
    hy: "Armenian",
    as: "Assamese",
    av: "Avaric",
    ae: "Avestan",
    ay: "Aymara",
    az: "Azerbaijani",
    bm: "Bambara",
    ba: "Bashkir",
    eu: "Basque",
    be: "Belarusian",
    bn: "Bengali (Bangla)",
    bh: "Bihari",
    bi: "Bislama",
    bs: "Bosnian",
    br: "Breton",
    bg: "Bulgarian",
    my: "Burmese",
    ca: "Catalan",
    ch: "Chamorro",
    ce: "Chechen",
    ny: "Chichewa, Chewa, Nyanja",
    zh: "Chinese",
    "zh-Hans": "Chinese (Simplified)",
    "zh-Hant": "Chinese (Traditional)",
    cv: "Chuvash",
    kw: "Cornish",
    co: "Corsican",
    cr: "Cree",
    hr: "Croatian",
    cs: "Czech",
    da: "Danish",
    dv: "Divehi, Dhivehi, Maldivian",
    nl: "Dutch",
    dz: "Dzongkha",
    en: "English",
    eo: "Esperanto",
    et: "Estonian",
    ee: "Ewe",
    fo: "Faroese",
    fj: "Fijian",
    fi: "Finnish",
    fr: "French",
    ff: "Fula, Fulah, Pulaar, Pular",
    gl: "Galician",
    gd: "Gaelic (Scottish)",
    gv: "Gaelic (Manx)",
    ka: "Georgian",
    de: "German",
    el: "Greek",
    kl: "Greenlandic",
    gn: "Guarani",
    gu: "Gujarati",
    ht: "Haitian Creole",
    ha: "Hausa",
    he: "Hebrew",
    hz: "Herero",
    hi: "Hindi",
    ho: "Hiri Motu",
    hu: "Hungarian",
    is: "Icelandic",
    io: "Ido",
    ig: "Igbo",
    id: "Indonesian",
    in: "Indonesian",
    ia: "Interlingua",
    ie: "Interlingue",
    iu: "Inuktitut",
    ik: "Inupiak",
    ga: "Irish",
    it: "Italian",
    ja: "Japanese",
    jv: "Javanese",
    kl: "Kalaallisut, Greenlandic",
    kn: "Kannada",
    kr: "Kanuri",
    ks: "Kashmiri",
    kk: "Kazakh",
    km: "Khmer",
    ki: "Kikuyu",
    rw: "Kinyarwanda (Rwanda)",
    rn: "Kirundi",
    ky: "Kyrgyz",
    kv: "Komi",
    kg: "Kongo",
    ko: "Korean",
    ku: "Kurdish",
    kj: "Kwanyama",
    lo: "Lao",
    la: "Latin",
    lv: "Latvian (Lettish)",
    li: "Limburgish ( Limburger)",
    ln: "Lingala",
    lt: "Lithuanian",
    lu: "Luga-Katanga",
    lg: "Luganda, Ganda",
    lb: "Luxembourgish",
    gv: "Manx",
    mk: "Macedonian",
    mg: "Malagasy",
    ms: "Malay",
    ml: "Malayalam",
    mt: "Maltese",
    mi: "Maori",
    mr: "Marathi",
    mh: "Marshallese",
    mo: "Moldavian",
    mn: "Mongolian",
    na: "Nauru",
    nv: "Navajo",
    ng: "Ndonga",
    nd: "Northern Ndebele",
    ne: "Nepali",
    no: "Norwegian",
    nb: "Norwegian bokmål",
    nn: "Norwegian nynorsk",
    ii: "Nuosu",
    oc: "Occitan",
    oj: "Ojibwe",
    cu: "Old Church Slavonic, Old Bulgarian",
    or: "Oriya",
    om: "Oromo (Afaan Oromo)",
    os: "Ossetian",
    pi: "Pāli",
    ps: "Pashto, Pushto",
    fa: "Persian (Farsi)",
    pl: "Polish",
    pt: "Portuguese",
    pa: "Punjabi (Eastern)",
    qu: "Quechua",
    rm: "Romansh",
    ro: "Romanian",
    ru: "Russian",
    se: "Sami",
    sm: "Samoan",
    sg: "Sango",
    sa: "Sanskrit",
    sr: "Serbian",
    sh: "Serbo-Croatian",
    st: "Sesotho",
    tn: "Setswana",
    sn: "Shona",
    ii: "Sichuan Yi",
    sd: "Sindhi",
    si: "Sinhalese",
    ss: "Siswati",
    sk: "Slovak",
    sl: "Slovenian",
    so: "Somali",
    nr: "Southern Ndebele",
    es: "Spanish",
    su: "Sundanese",
    sw: "Swahili (Kiswahili)",
    ss: "Swati",
    sv: "Swedish",
    tl: "Tagalog",
    ty: "Tahitian",
    tg: "Tajik",
    ta: "Tamil",
    tt: "Tatar",
    te: "Telugu",
    th: "Thai",
    bo: "Tibetan",
    ti: "Tigrinya",
    to: "Tonga",
    ts: "Tsonga",
    tr: "Turkish",
    tk: "Turkmen",
    tw: "Twi",
    ug: "Uyghur",
    uk: "Ukrainian",
    ur: "Urdu",
    uz: "Uzbek",
    ve: "Venda",
    vi: "Vietnamese",
    vo: "Volapük",
    wa: "Wallon",
    cy: "Welsh",
    wo: "Wolof",
    fy: "Western Frisian",
    xh: "Xhosa",
    yi: "Yiddish",
    ji: "Yiddish",
    yo: "Yoruba",
    za: "Zhuang, Chuang",
    zu: "Zulu",
}

// DE, FR, IT ... from https://github.com/Planeshifter/text-miner/blob/master/data/stopwords.json 
const notKeywords = [
    "error", "", "not", "在", "再", "的", "地", "得", "不", "他", "他們", "她", "她們", "它", "它們", "們", "牠", "牠們", "我", "我們", "你", "你們", "妳", "妳們", "自",
    "a",
    "ab",
    "aber",
    "aber",
    "ach",
    "acht",
    "achte",
    "achten",
    "achter",
    "achtes",
    "ag",
    "alle",
    "allein",
    "allem",
    "allen",
    "aller",
    "allerdings",
    "alles",
    "allgemeinen",
    "als",
    "als",
    "also",
    "am",
    "an",
    "andere",
    "anderen",
    "andern",
    "anders",
    "au",
    "auch",
    "auch",
    "auf",
    "aus",
    "ausser",
    "außer",
    "ausserdem",
    "außerdem",
    "b",
    "bald",
    "bei",
    "beide",
    "beiden",
    "beim",
    "beispiel",
    "bekannt",
    "bereits",
    "besonders",
    "besser",
    "besten",
    "bin",
    "bis",
    "bisher",
    "bist",
    "c",
    "d",
    "da",
    "dabei",
    "dadurch",
    "dafür",
    "dagegen",
    "daher",
    "dahin",
    "dahinter",
    "damals",
    "damit",
    "danach",
    "daneben",
    "dank",
    "dann",
    "daran",
    "darauf",
    "daraus",
    "darf",
    "darfst",
    "darin",
    "darüber",
    "darum",
    "darunter",
    "das",
    "das",
    "dasein",
    "daselbst",
    "dass",
    "daß",
    "dasselbe",
    "davon",
    "davor",
    "dazu",
    "dazwischen",
    "dein",
    "deine",
    "deinem",
    "deiner",
    "dem",
    "dementsprechend",
    "demgegenüber",
    "demgemäss",
    "demgemäß",
    "demselben",
    "demzufolge",
    "den",
    "denen",
    "denn",
    "denn",
    "denselben",
    "der",
    "deren",
    "derjenige",
    "derjenigen",
    "dermassen",
    "dermaßen",
    "derselbe",
    "derselben",
    "des",
    "deshalb",
    "desselben",
    "dessen",
    "deswegen",
    "d.h",
    "dich",
    "die",
    "diejenige",
    "diejenigen",
    "dies",
    "diese",
    "dieselbe",
    "dieselben",
    "diesem",
    "diesen",
    "dieser",
    "dieses",
    "dir",
    "doch",
    "dort",
    "drei",
    "drin",
    "dritte",
    "dritten",
    "dritter",
    "drittes",
    "du",
    "durch",
    "durchaus",
    "dürfen",
    "dürft",
    "durfte",
    "durften",
    "e",
    "eben",
    "ebenso",
    "ehrlich",
    "ei",
    "ei,",
    "ei,",
    "eigen",
    "eigene",
    "eigenen",
    "eigener",
    "eigenes",
    "ein",
    "einander",
    "eine",
    "einem",
    "einen",
    "einer",
    "eines",
    "einige",
    "einigen",
    "einiger",
    "einiges",
    "einmal",
    "einmal",
    "eins",
    "elf",
    "en",
    "ende",
    "endlich",
    "entweder",
    "entweder",
    "er",
    "Ernst",
    "erst",
    "erste",
    "ersten",
    "erster",
    "erstes",
    "es",
    "etwa",
    "etwas",
    "euch",
    "f",
    "früher",
    "fünf",
    "fünfte",
    "fünften",
    "fünfter",
    "fünftes",
    "für",
    "g",
    "gab",
    "ganz",
    "ganze",
    "ganzen",
    "ganzer",
    "ganzes",
    "gar",
    "gedurft",
    "gegen",
    "gegenüber",
    "gehabt",
    "gehen",
    "geht",
    "gekannt",
    "gekonnt",
    "gemacht",
    "gemocht",
    "gemusst",
    "genug",
    "gerade",
    "gern",
    "gesagt",
    "gesagt",
    "geschweige",
    "gewesen",
    "gewollt",
    "geworden",
    "gibt",
    "ging",
    "gleich",
    "gott",
    "gross",
    "groß",
    "grosse",
    "große",
    "grossen",
    "großen",
    "grosser",
    "großer",
    "grosses",
    "großes",
    "gut",
    "gute",
    "guter",
    "gutes",
    "h",
    "habe",
    "haben",
    "habt",
    "hast",
    "hat",
    "hatte",
    "hätte",
    "hatten",
    "hätten",
    "heisst",
    "her",
    "heute",
    "hier",
    "hin",
    "hinter",
    "hoch",
    "i",
    "ich",
    "ihm",
    "ihn",
    "ihnen",
    "ihr",
    "ihre",
    "ihrem",
    "ihren",
    "ihrer",
    "ihres",
    "im",
    "im",
    "immer",
    "in",
    "in",
    "indem",
    "infolgedessen",
    "ins",
    "irgend",
    "ist",
    "j",
    "ja",
    "ja",
    "jahr",
    "jahre",
    "jahren",
    "je",
    "jede",
    "jedem",
    "jeden",
    "jeder",
    "jedermann",
    "jedermanns",
    "jedoch",
    "jemand",
    "jemandem",
    "jemanden",
    "jene",
    "jenem",
    "jenen",
    "jener",
    "jenes",
    "jetzt",
    "k",
    "kam",
    "kann",
    "kannst",
    "kaum",
    "kein",
    "keine",
    "keinem",
    "keinen",
    "keiner",
    "kleine",
    "kleinen",
    "kleiner",
    "kleines",
    "kommen",
    "kommt",
    "können",
    "könnt",
    "konnte",
    "könnte",
    "konnten",
    "kurz",
    "l",
    "lang",
    "lange",
    "lange",
    "leicht",
    "leide",
    "lieber",
    "los",
    "m",
    "machen",
    "macht",
    "machte",
    "mag",
    "magst",
    "mahn",
    "man",
    "manche",
    "manchem",
    "manchen",
    "mancher",
    "manches",
    "mann",
    "mehr",
    "mein",
    "meine",
    "meinem",
    "meinen",
    "meiner",
    "meines",
    "mensch",
    "menschen",
    "mich",
    "mir",
    "mit",
    "mittel",
    "mochte",
    "möchte",
    "mochten",
    "mögen",
    "möglich",
    "mögt",
    "morgen",
    "muss",
    "muß",
    "müssen",
    "musst",
    "müsst",
    "musste",
    "mussten",
    "n",
    "na",
    "nach",
    "nachdem",
    "nahm",
    "natürlich",
    "neben",
    "nein",
    "neue",
    "neuen",
    "neun",
    "neunte",
    "neunten",
    "neunter",
    "neuntes",
    "nicht",
    "nicht",
    "nichts",
    "nie",
    "niemand",
    "niemandem",
    "niemanden",
    "noch",
    "nun",
    "nun",
    "nur",
    "o",
    "ob",
    "ob",
    "oben",
    "oder",
    "oder",
    "offen",
    "oft",
    "oft",
    "ohne",
    "Ordnung",
    "p",
    "q",
    "r",
    "recht",
    "rechte",
    "rechten",
    "rechter",
    "rechtes",
    "richtig",
    "rund",
    "s",
    "sa",
    "sache",
    "sagt",
    "sagte",
    "sah",
    "satt",
    "schlecht",
    "Schluss",
    "schon",
    "sechs",
    "sechste",
    "sechsten",
    "sechster",
    "sechstes",
    "sehr",
    "sei",
    "sei",
    "seid",
    "seien",
    "sein",
    "seine",
    "seinem",
    "seinen",
    "seiner",
    "seines",
    "seit",
    "seitdem",
    "selbst",
    "selbst",
    "sich",
    "sie",
    "sieben",
    "siebente",
    "siebenten",
    "siebenter",
    "siebentes",
    "sind",
    "so",
    "solang",
    "solche",
    "solchem",
    "solchen",
    "solcher",
    "solches",
    "soll",
    "sollen",
    "sollte",
    "sollten",
    "sondern",
    "sonst",
    "sowie",
    "später",
    "statt",
    "t",
    "tag",
    "tage",
    "tagen",
    "tat",
    "teil",
    "tel",
    "tritt",
    "trotzdem",
    "tun",
    "u",
    "über",
    "überhaupt",
    "übrigens",
    "uhr",
    "um",
    "und",
    "und?",
    "uns",
    "unser",
    "unsere",
    "unserer",
    "unter",
    "v",
    "vergangenen",
    "viel",
    "viele",
    "vielem",
    "vielen",
    "vielleicht",
    "vier",
    "vierte",
    "vierten",
    "vierter",
    "viertes",
    "vom",
    "von",
    "vor",
    "w",
    "wahr?",
    "während",
    "währenddem",
    "währenddessen",
    "wann",
    "war",
    "wäre",
    "waren",
    "wart",
    "warum",
    "was",
    "wegen",
    "weil",
    "weit",
    "weiter",
    "weitere",
    "weiteren",
    "weiteres",
    "welche",
    "welchem",
    "welchen",
    "welcher",
    "welches",
    "wem",
    "wen",
    "wenig",
    "wenig",
    "wenige",
    "weniger",
    "weniges",
    "wenigstens",
    "wenn",
    "wenn",
    "wer",
    "werde",
    "werden",
    "werdet",
    "wessen",
    "wie",
    "wie",
    "wieder",
    "will",
    "willst",
    "wir",
    "wird",
    "wirklich",
    "wirst",
    "wo",
    "wohl",
    "wollen",
    "wollt",
    "wollte",
    "wollten",
    "worden",
    "wurde",
    "würde",
    "wurden",
    "würden",
    "x",
    "y",
    "z",
    "z.b",
    "zehn",
    "zehnte",
    "zehnten",
    "zehnter",
    "zehntes",
    "zeit",
    "zu",
    "zuerst",
    "zugleich",
    "zum",
    "zum",
    "zunächst",
    "zur",
    "zurück",
    "zusammen",
    "zwanzig",
    "zwar",
    "zwar",
    "zwei",
    "zweite",
    "zweiten",
    "zweiter",
    "zweites",
    "zwischen",
    "zwölf",
    "él",
    "ésta",
    "éstas",
    "éste",
    "éstos",
    "última",
    "últimas",
    "último",
    "últimos",
    "a",
    "añadió",
    "aún",
    "actualmente",
    "adelante",
    "además",
    "afirmó",
    "agregó",
    "ahí",
    "ahora",
    "al",
    "algún",
    "algo",
    "alguna",
    "algunas",
    "alguno",
    "algunos",
    "alrededor",
    "ambos",
    "ante",
    "anterior",
    "antes",
    "apenas",
    "aproximadamente",
    "aquí",
    "así",
    "aseguró",
    "aunque",
    "ayer",
    "bajo",
    "bien",
    "buen",
    "buena",
    "buenas",
    "bueno",
    "buenos",
    "cómo",
    "cada",
    "casi",
    "cerca",
    "cierto",
    "cinco",
    "comentó",
    "como",
    "con",
    "conocer",
    "consideró",
    "considera",
    "contra",
    "cosas",
    "creo",
    "cual",
    "cuales",
    "cualquier",
    "cuando",
    "cuanto",
    "cuatro",
    "cuenta",
    "da",
    "dado",
    "dan",
    "dar",
    "de",
    "debe",
    "deben",
    "debido",
    "decir",
    "dejó",
    "del",
    "demás",
    "dentro",
    "desde",
    "después",
    "dice",
    "dicen",
    "dicho",
    "dieron",
    "diferente",
    "diferentes",
    "dijeron",
    "dijo",
    "dio",
    "donde",
    "dos",
    "durante",
    "e",
    "ejemplo",
    "el",
    "ella",
    "ellas",
    "ello",
    "ellos",
    "embargo",
    "en",
    "encuentra",
    "entonces",
    "entre",
    "era",
    "eran",
    "es",
    "esa",
    "esas",
    "ese",
    "eso",
    "esos",
    "está",
    "están",
    "esta",
    "estaba",
    "estaban",
    "estamos",
    "estar",
    "estará",
    "estas",
    "este",
    "esto",
    "estos",
    "estoy",
    "estuvo",
    "ex",
    "existe",
    "existen",
    "explicó",
    "expresó",
    "fin",
    "fue",
    "fuera",
    "fueron",
    "gran",
    "grandes",
    "ha",
    "había",
    "habían",
    "haber",
    "habrá",
    "hace",
    "hacen",
    "hacer",
    "hacerlo",
    "hacia",
    "haciendo",
    "han",
    "hasta",
    "hay",
    "haya",
    "he",
    "hecho",
    "hemos",
    "hicieron",
    "hizo",
    "hoy",
    "hubo",
    "igual",
    "incluso",
    "indicó",
    "informó",
    "junto",
    "la",
    "lado",
    "las",
    "le",
    "les",
    "llegó",
    "lleva",
    "llevar",
    "lo",
    "los",
    "luego",
    "lugar",
    "más",
    "manera",
    "manifestó",
    "mayor",
    "me",
    "mediante",
    "mejor",
    "mencionó",
    "menos",
    "mi",
    "mientras",
    "misma",
    "mismas",
    "mismo",
    "mismos",
    "momento",
    "mucha",
    "muchas",
    "mucho",
    "muchos",
    "muy",
    "nada",
    "nadie",
    "ni",
    "ningún",
    "ninguna",
    "ningunas",
    "ninguno",
    "ningunos",
    "no",
    "nos",
    "nosotras",
    "nosotros",
    "nuestra",
    "nuestras",
    "nuestro",
    "nuestros",
    "nueva",
    "nuevas",
    "nuevo",
    "nuevos",
    "nunca",
    "o",
    "ocho",
    "otra",
    "otras",
    "otro",
    "otros",
    "para",
    "parece",
    "parte",
    "partir",
    "pasada",
    "pasado",
    "pero",
    "pesar",
    "poca",
    "pocas",
    "poco",
    "pocos",
    "podemos",
    "podrá",
    "podrán",
    "podría",
    "podrían",
    "poner",
    "por",
    "porque",
    "posible",
    "próximo",
    "próximos",
    "primer",
    "primera",
    "primero",
    "primeros",
    "principalmente",
    "propia",
    "propias",
    "propio",
    "propios",
    "pudo",
    "pueda",
    "puede",
    "pueden",
    "pues",
    "qué",
    "que",
    "quedó",
    "queremos",
    "quién",
    "quien",
    "quienes",
    "quiere",
    "realizó",
    "realizado",
    "realizar",
    "respecto",
    "sí",
    "sólo",
    "se",
    "señaló",
    "sea",
    "sean",
    "según",
    "segunda",
    "segundo",
    "seis",
    "ser",
    "será",
    "serán",
    "sería",
    "si",
    "sido",
    "siempre",
    "siendo",
    "siete",
    "sigue",
    "siguiente",
    "sin",
    "sino",
    "sobre",
    "sola",
    "solamente",
    "solas",
    "solo",
    "solos",
    "son",
    "su",
    "sus",
    "tal",
    "también",
    "tampoco",
    "tan",
    "tanto",
    "tenía",
    "tendrá",
    "tendrán",
    "tenemos",
    "tener",
    "tenga",
    "tengo",
    "tenido",
    "tercera",
    "tiene",
    "tienen",
    "toda",
    "todas",
    "todavía",
    "todo",
    "todos",
    "total",
    "tras",
    "trata",
    "través",
    "tres",
    "tuvo",
    "un",
    "una",
    "unas",
    "uno",
    "unos",
    "usted",
    "va",
    "vamos",
    "van",
    "varias",
    "varios",
    "veces",
    "ver",
    "vez",
    "y",
    "ya",
    "yo",
    "a",
    "abbastanza",
    "accidenti",
    "ad",
    "adesso",
    "affinche",
    "agli",
    "ahime",
    "ahimÃ¨",
    "ai",
    "al",
    "alcuna",
    "alcuni",
    "alcuno",
    "all",
    "alla",
    "alle",
    "allo",
    "altri",
    "altrimenti",
    "altro",
    "altrui",
    "anche",
    "ancora",
    "anni",
    "anno",
    "ansa",
    "assai",
    "attesa",
    "avanti",
    "avendo",
    "avente",
    "aver",
    "avere",
    "avete",
    "aveva",
    "avuta",
    "avute",
    "avuti",
    "avuto",
    "basta",
    "bene",
    "benissimo",
    "berlusconi",
    "brava",
    "bravo",
    "c",
    "casa",
    "caso",
    "cento",
    "certa",
    "certe",
    "certi",
    "certo",
    "che",
    "chi",
    "chicchessia",
    "chiunque",
    "ci",
    "ciascuna",
    "ciascuno",
    "cima",
    "cio",
    "ciÃ²",
    "cioe",
    "cioÃ¨",
    "circa",
    "citta",
    "cittÃ ",
    "codesta",
    "codesti",
    "codesto",
    "cogli",
    "coi",
    "col",
    "colei",
    "coll",
    "coloro",
    "colui",
    "come",
    "con",
    "concernente",
    "consiglio",
    "contro",
    "cortesia",
    "cos",
    "cosa",
    "cosi",
    "cosÃ¬",
    "cui",
    "d",
    "da",
    "dagli",
    "dai",
    "dal",
    "dall",
    "dalla",
    "dalle",
    "dallo",
    "davanti",
    "degli",
    "dei",
    "del",
    "dell",
    "della",
    "delle",
    "dello",
    "dentro",
    "detto",
    "deve",
    "di",
    "dice",
    "dietro",
    "dire",
    "dirimpetto",
    "dopo",
    "dove",
    "dovra",
    "dovrÃ ",
    "due",
    "dunque",
    "durante",
    "e",
    "Ã¨",
    "ecco",
    "ed",
    "egli",
    "ella",
    "eppure",
    "era",
    "erano",
    "esse",
    "essendo",
    "esser",
    "essere",
    "essi",
    "ex",
    "fa",
    "fare",
    "fatto",
    "favore",
    "fin",
    "finalmente",
    "finche",
    "fine",
    "fino",
    "forse",
    "fra",
    "fuori",
    "gia",
    "giÃ ",
    "giacche",
    "giorni",
    "giorno",
    "gli",
    "gliela",
    "gliele",
    "glieli",
    "glielo",
    "gliene",
    "governo",
    "grande",
    "grazie",
    "gruppo",
    "ha",
    "hai",
    "hanno",
    "ho",
    "i",
    "ieri",
    "il",
    "improvviso",
    "in",
    "infatti",
    "insieme",
    "intanto",
    "intorno",
    "invece",
    "io",
    "l",
    "la",
    "lÃ ",
    "lavoro",
    "le",
    "lei",
    "li",
    "lo",
    "lontano",
    "loro",
    "lui",
    "lungo",
    "ma",
    "macche",
    "magari",
    "mai",
    "male",
    "malgrado",
    "malissimo",
    "me",
    "medesimo",
    "mediante",
    "meglio",
    "meno",
    "mentre",
    "mesi",
    "mezzo",
    "mi",
    "mia",
    "mie",
    "miei",
    "mila",
    "miliardi",
    "milioni",
    "ministro",
    "mio",
    "moltissimo",
    "molto",
    "mondo",
    "nazionale",
    "ne",
    "negli",
    "nei",
    "nel",
    "nell",
    "nella",
    "nelle",
    "nello",
    "nemmeno",
    "neppure",
    "nessuna",
    "nessuno",
    "niente",
    "no",
    "noi",
    "non",
    "nondimeno",
    "nostra",
    "nostre",
    "nostri",
    "nostro",
    "nulla",
    "nuovo",
    "o",
    "od",
    "oggi",
    "ogni",
    "ognuna",
    "ognuno",
    "oltre",
    "oppure",
    "ora",
    "ore",
    "osi",
    "ossia",
    "paese",
    "parecchi",
    "parecchie",
    "parecchio",
    "parte",
    "partendo",
    "peccato",
    "peggio",
    "per",
    "perche",
    "perchÃ¨",
    "percio",
    "perciÃ²",
    "perfino",
    "pero",
    "perÃ²",
    "persone",
    "piedi",
    "pieno",
    "piglia",
    "piu",
    "piÃ¹",
    "po",
    "pochissimo",
    "poco",
    "poi",
    "poiche",
    "press",
    "prima",
    "primo",
    "proprio",
    "puo",
    "puÃ²",
    "pure",
    "purtroppo",
    "qualche",
    "qualcuna",
    "qualcuno",
    "quale",
    "quali",
    "qualunque",
    "quando",
    "quanta",
    "quante",
    "quanti",
    "quanto",
    "quantunque",
    "quasi",
    "quattro",
    "quel",
    "quella",
    "quelli",
    "quello",
    "quest",
    "questa",
    "queste",
    "questi",
    "questo",
    "qui",
    "quindi",
    "riecco",
    "salvo",
    "sara",
    "sarÃ ",
    "sarebbe",
    "scopo",
    "scorso",
    "se",
    "secondo",
    "seguente",
    "sei",
    "sempre",
    "senza",
    "si",
    "sia",
    "siamo",
    "siete",
    "solito",
    "solo",
    "sono",
    "sopra",
    "sotto",
    "sta",
    "staranno",
    "stata",
    "state",
    "stati",
    "stato",
    "stesso",
    "su",
    "sua",
    "successivo",
    "sue",
    "sugli",
    "sui",
    "sul",
    "sull",
    "sulla",
    "sulle",
    "sullo",
    "suo",
    "suoi",
    "tale",
    "talvolta",
    "tanto",
    "te",
    "tempo",
    "ti",
    "torino",
    "tra",
    "tranne",
    "tre",
    "troppo",
    "tu",
    "tua",
    "tue",
    "tuo",
    "tuoi",
    "tutta",
    "tuttavia",
    "tutte",
    "tutti",
    "tutto",
    "uguali",
    "un",
    "una",
    "uno",
    "uomo",
    "va",
    "vale",
    "varia",
    "varie",
    "vario",
    "verso",
    "vi",
    "via",
    "vicino",
    "visto",
    "vita",
    "voi",
    "volta",
    "vostra",
    "vostre",
    "vostri",
    "vostro"
];